// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CSG.MI.FDW.EF.Migrations
{
    [DbContext(typeof(HQDbContext))]
    [Migration("20240422061845_Coordinate_histroies")]
    partial class Coordinate_histroies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hq")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Department.DeptEntity", b =>
                {
                    b.Property<string>("DeptId")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("dept_id");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dept_name");

                    b.Property<string>("Dept_Central")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("dept_cntr");

                    b.Property<string>("Dept_Company")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("dept_cmp");

                    b.Property<string>("Dept_Group")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("dept_grp");

                    b.Property<string>("Dept_Organization")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("dept_org");

                    b.Property<string>("Dept_Team")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("dept_team");

                    b.Property<DateTime>("EditDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("edit_dt")
                        .HasDefaultValueSql("current_timestamp");

                    b.HasKey("DeptId")
                        .HasName("dept_mst_pkey");

                    b.ToTable("dept_mst", "dept");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Department.DeptRnREntity", b =>
                {
                    b.Property<string>("DeptId")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("dept_id");

                    b.Property<string>("Ability")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ability");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EditDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("edit_dt")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Job")
                        .HasColumnType("text")
                        .HasColumnName("job");

                    b.HasKey("DeptId")
                        .HasName("dept_rnr_pkey");

                    b.ToTable("dept_rnr", "dept");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Feedback.CategoryEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("key");

                    b.Property<DateTime>("EditDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("edit_dt")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Value_Eng")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("value_eng");

                    b.Property<string>("Value_Kor")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("value_kor");

                    b.HasKey("Key")
                        .HasName("PK_category");

                    b.ToTable("category_mst", "feedback");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Feedback.FeedbackEntity", b =>
                {
                    b.Property<long?>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BigInt")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Seq"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("category");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("EditDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("edit_dt")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<int>("System")
                        .HasColumnType("integer")
                        .HasColumnName("system");

                    b.HasKey("Seq")
                        .HasName("PK_feedback");

                    b.HasIndex("Category");

                    b.HasIndex("EditDate")
                        .HasDatabaseName("IX_feedback_edit_date");

                    b.HasIndex("System");

                    b.ToTable("user_feedback", "feedback");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Feedback.SystemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK_system");

                    b.ToTable("system", "feedback");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.IoT.DeviceEntity", b =>
                {
                    b.Property<string>("CompanyCd")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("company_cd");

                    b.Property<string>("Descn")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descn");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.Property<string>("MachId")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("mach_id");

                    b.ToTable("device", "iot");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.IoT.MachineEntity", b =>
                {
                    b.Property<string>("CompanyCd")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("company_cd");

                    b.Property<string>("Descn")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descn");

                    b.Property<string>("LineCd")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("line_cd");

                    b.Property<string>("LocCd")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("loc_cd");

                    b.Property<string>("MachId")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("mach_id");

                    b.Property<string>("MachKind")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("mach_kind");

                    b.Property<string>("MachName")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("mach_name");

                    b.Property<string>("OpCd")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("op_cd");

                    b.Property<string>("OrgnCd")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("orgn_cd");

                    b.Property<string>("mLineCd")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mline_cd");

                    b.ToTable("machine", "iot");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.IoT.SensorEntity", b =>
                {
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("addr");

                    b.Property<string>("CompanyCd")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("company_cd");

                    b.Property<string>("Descn")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descn");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.Property<string>("MachId")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("mach_id");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("topic");

                    b.ToTable("sensor", "iot");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.IoT.TemperatureEntity", b =>
                {
                    b.Property<DateTime>("CaptureDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("capture_dt");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("device_id");

                    b.Property<string>("Hmsf")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("hmsf");

                    b.Property<float>("Humidity")
                        .HasColumnType("real")
                        .HasColumnName("t2");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("sensor_id");

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasColumnName("t1");

                    b.Property<string>("Ymd")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ymd");

                    b.HasIndex(new[] { "DeviceId", "CaptureDate" }, "idx_multi_temperature");

                    b.HasIndex(new[] { "CaptureDate" }, "idx_temperature");

                    b.ToTable("temperature", "iot");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.DataMart.DailyStatusEntity", b =>
                {
                    b.Property<string>("Factory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("factory");

                    b.Property<string>("OpCd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opcd");

                    b.Property<string>("OpLocalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("oplocalname");

                    b.Property<string>("OpName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opname");

                    b.Property<decimal>("PlanCnt")
                        .HasColumnType("numeric")
                        .HasColumnName("plancnt");

                    b.Property<decimal>("PlanQty")
                        .HasColumnType("numeric")
                        .HasColumnName("planqty");

                    b.Property<decimal?>("ProdCnt")
                        .HasColumnType("numeric")
                        .HasColumnName("prodcnt");

                    b.Property<decimal?>("ProdQty")
                        .HasColumnType("numeric")
                        .HasColumnName("prodqty");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("numeric")
                        .HasColumnName("rate");

                    b.ToTable("dailystatus", "services");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.DataMart.FactoryPlnTotalEntity", b =>
                {
                    b.Property<string>("Factory")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("factory");

                    b.Property<long>("TotalCnt")
                        .HasColumnType("bigint")
                        .HasColumnName("cnt");

                    b.Property<decimal>("TotalQty")
                        .HasColumnType("numeric")
                        .HasColumnName("qty");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("year");

                    b.ToTable("pln_tot", "services");

                    b.ToView("pln_tot", "services");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.DataMart.FactoryPrfTotalEntity", b =>
                {
                    b.Property<string>("Factory")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("factory");

                    b.Property<long>("TotalCnt")
                        .HasColumnType("bigint")
                        .HasColumnName("cnt");

                    b.Property<decimal>("TotalQty")
                        .HasColumnType("numeric")
                        .HasColumnName("qty");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("year");

                    b.ToTable("prf_tot", "services");

                    b.ToView("prf_tot", "services");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.DataMart.WsCoodinateEntity", b =>
                {
                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coordi_sys");

                    b.Property<string>("PassType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passtype");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("WsNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wsno");

                    b.Property<string>("opcd")
                        .HasColumnType("text")
                        .HasColumnName("opcd");

                    b.Property<string>("tagId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tagid");

                    b.Property<string>("x")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position_x");

                    b.Property<string>("y")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position_y");

                    b.ToTable("worksheets_coordinate", "services");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.DataMart.WsCoordinateHistoryEntity", b =>
                {
                    b.Property<string>("Floor")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("floor");

                    b.Property<TimeSpan?>("LeadTime")
                        .HasColumnType("interval")
                        .HasColumnName("diff");

                    b.Property<DateTime>("Next")
                        .HasColumnType("timestamp")
                        .HasColumnName("next");

                    b.Property<DateTime>("Now")
                        .HasColumnType("timestamp")
                        .HasColumnName("now");

                    b.Property<string>("Opcd")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("opcd");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("status");

                    b.Property<string>("TagId")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("tagid");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("tag_type");

                    b.Property<string>("WsNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("wsno");

                    b.Property<string>("Zone")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("zone");

                    b.ToTable("worksheets_coordinate_history", "services");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.DataMart.WsDetailEntity", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ColorVer")
                        .HasColumnType("text")
                        .HasColumnName("color_ver");

                    b.Property<string>("DevColorwayId")
                        .HasColumnType("text")
                        .HasColumnName("dev_colorway_id");

                    b.Property<string>("DevName")
                        .HasColumnType("text")
                        .HasColumnName("dev_name");

                    b.Property<string>("DevStyleNumber")
                        .HasColumnType("text")
                        .HasColumnName("dev_style_number");

                    b.Property<string>("Dpa")
                        .HasColumnType("text")
                        .HasColumnName("dpa");

                    b.Property<string>("Factory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("factory");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("bom_id");

                    b.Property<string>("ModelId")
                        .HasColumnType("text")
                        .HasColumnName("model_id");

                    b.Property<string>("NikeDev")
                        .HasColumnType("text")
                        .HasColumnName("nike_dev");

                    b.Property<decimal?>("NikeSendQty")
                        .HasColumnType("numeric)")
                        .HasColumnName("nike_send_qty");

                    b.Property<string>("PM")
                        .HasColumnType("text")
                        .HasColumnName("pcc_pm");

                    b.Property<string>("PatternId")
                        .HasColumnType("text")
                        .HasColumnName("pattern_id");

                    b.Property<string>("PccOrg")
                        .HasColumnType("text")
                        .HasColumnName("pcc_org");

                    b.Property<string>("PmName")
                        .HasColumnType("text")
                        .HasColumnName("pm_name");

                    b.Property<string>("ProdFactory")
                        .HasColumnType("text")
                        .HasColumnName("prod_factory");

                    b.Property<string>("Rev")
                        .HasColumnType("text")
                        .HasColumnName("bom_rev");

                    b.Property<string>("ReworkYN")
                        .HasColumnType("text")
                        .HasColumnName("rework_yn");

                    b.Property<string>("SampleEts")
                        .HasColumnType("text")
                        .HasColumnName("sample_ets");

                    b.Property<decimal?>("SampleQty")
                        .HasColumnType("numeric")
                        .HasColumnName("sample_qty");

                    b.Property<string>("SampleSize")
                        .HasColumnType("text")
                        .HasColumnName("sample_size");

                    b.Property<string>("Season")
                        .HasColumnType("text")
                        .HasColumnName("season_cd");

                    b.Property<string>("StCd")
                        .HasColumnType("text")
                        .HasColumnName("st_cd");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StyleCd")
                        .HasColumnType("text")
                        .HasColumnName("style_cd");

                    b.Property<string>("SubStCd")
                        .HasColumnType("text")
                        .HasColumnName("sub_st_cd");

                    b.Property<string>("TD")
                        .HasColumnType("text")
                        .HasColumnName("td");

                    b.Property<string>("WsNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ws_no");

                    b.Property<decimal?>("WsQty")
                        .HasColumnType("numeric")
                        .HasColumnName("ws_qty");

                    b.Property<string>("WsStatus")
                        .HasColumnType("text")
                        .HasColumnName("ws_status");

                    b.HasIndex(new[] { "Category" }, "idx_dtl_category");

                    b.HasIndex(new[] { "ColorVer" }, "idx_dtl_color");

                    b.HasIndex(new[] { "DevColorwayId" }, "idx_dtl_colorway");

                    b.HasIndex(new[] { "DevName" }, "idx_dtl_devname");

                    b.HasIndex(new[] { "DevStyleNumber" }, "idx_dtl_devstyle_num");

                    b.HasIndex(new[] { "ModelId" }, "idx_dtl_model");

                    b.HasIndex(new[] { "PM" }, "idx_dtl_pm");

                    b.HasIndex(new[] { "PmName" }, "idx_dtl_pm_kor");

                    b.HasIndex(new[] { "SampleEts" }, "idx_dtl_sample_ets");

                    b.HasIndex(new[] { "Season" }, "idx_dtl_season");

                    b.HasIndex(new[] { "StCd" }, "idx_dtl_st");

                    b.HasIndex(new[] { "SubStCd" }, "idx_dtl_st_sub");

                    b.HasIndex(new[] { "StyleCd" }, "idx_dtl_style");

                    b.HasIndex(new[] { "WsNo" }, "idx_dtl_ws");

                    b.ToTable("worksheets_detail", "services");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.DataMart.WsEntity", b =>
                {
                    b.Property<string>("Factory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("factory");

                    b.Property<string>("WsNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wsno");

                    b.ToTable("worksheets", "services");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.DataMart.WsHistoryEntity", b =>
                {
                    b.Property<string>("Factory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("factory");

                    b.Property<string>("OpCd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opcd");

                    b.Property<string>("OpChk")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opchk");

                    b.Property<string>("OpLocalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("oplocalname");

                    b.Property<string>("OpName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opname");

                    b.Property<string>("PlanDate")
                        .HasColumnType("text")
                        .HasColumnName("plandate");

                    b.Property<string>("ProdDate")
                        .HasColumnType("text")
                        .HasColumnName("proddate");

                    b.Property<string>("ProdTime")
                        .HasColumnType("text")
                        .HasColumnName("prodtime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("WsNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wsno");

                    b.ToTable("worksheets_history", "services");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.DataMart.WsRateEntity", b =>
                {
                    b.Property<decimal>("OpCatacity")
                        .HasColumnType("numeric")
                        .HasColumnName("op_capacity");

                    b.Property<string>("OpCd")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("op_cd");

                    b.Property<decimal>("OpLeadTime")
                        .HasColumnType("numeric")
                        .HasColumnName("op_leadtime");

                    b.Property<string>("OpLocalName")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("op_local_name");

                    b.Property<string>("OpName")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("op_name");

                    b.Property<long>("aCnt")
                        .HasColumnType("bigint")
                        .HasColumnName("a_cnt");

                    b.Property<decimal>("aQty")
                        .HasColumnType("numeric")
                        .HasColumnName("a_qty");

                    b.Property<long>("dCnt")
                        .HasColumnType("bigint")
                        .HasColumnName("d_cnt");

                    b.Property<decimal>("dQty")
                        .HasColumnType("numeric")
                        .HasColumnName("d_qty");

                    b.Property<long>("hCnt")
                        .HasColumnType("bigint")
                        .HasColumnName("h_cnt");

                    b.Property<decimal>("hQty")
                        .HasColumnType("numeric")
                        .HasColumnName("h_qty");

                    b.Property<long>("iCnt")
                        .HasColumnType("bigint")
                        .HasColumnName("i_cnt");

                    b.Property<decimal>("iQty")
                        .HasColumnType("numeric")
                        .HasColumnName("i_qty");

                    b.Property<long>("kCnt")
                        .HasColumnType("bigint")
                        .HasColumnName("k_cnt");

                    b.Property<decimal>("kQty")
                        .HasColumnType("numeric")
                        .HasColumnName("k_qty");

                    b.Property<long>("oCnt")
                        .HasColumnType("bigint")
                        .HasColumnName("o_cnt");

                    b.Property<decimal>("oQty")
                        .HasColumnType("numeric")
                        .HasColumnName("o_qty");

                    b.Property<long>("pCnt")
                        .HasColumnType("bigint")
                        .HasColumnName("p_cnt");

                    b.Property<decimal>("pQty")
                        .HasColumnType("numeric")
                        .HasColumnName("p_qty");

                    b.Property<long>("sCnt")
                        .HasColumnType("bigint")
                        .HasColumnName("s_cnt");

                    b.Property<decimal>("sQty")
                        .HasColumnType("numeric")
                        .HasColumnName("s_qty");

                    b.Property<long>("tCnt")
                        .HasColumnType("bigint")
                        .HasColumnName("t_cnt");

                    b.Property<decimal>("tQty")
                        .HasColumnType("numeric")
                        .HasColumnName("t_qty");

                    b.ToTable("worksheets_rate", "services");

                    b.ToView("worksheets_rate", "services");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.DataMart.WsStatusEntity", b =>
                {
                    b.Property<string>("OpCd")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("opcd");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("numeric")
                        .HasColumnName("qty");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("status");

                    b.Property<string>("TagId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tagid");

                    b.Property<string>("Ws")
                        .HasColumnType("text")
                        .HasColumnName("wsno");

                    b.ToTable("worksheets_status", "services");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.DataMart.WsSummaryEntity", b =>
                {
                    b.Property<string>("BomId")
                        .HasColumnType("text")
                        .HasColumnName("bomid");

                    b.Property<string>("DevColorwayId")
                        .HasColumnType("text")
                        .HasColumnName("devcolorwayid");

                    b.Property<string>("Factory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("factory");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("OpCd")
                        .HasColumnType("text")
                        .HasColumnName("opcd");

                    b.Property<string>("OpLocalName")
                        .HasColumnType("text")
                        .HasColumnName("op_local_name");

                    b.Property<string>("OpName")
                        .HasColumnType("text")
                        .HasColumnName("op_name");

                    b.Property<string>("PlanDate")
                        .HasColumnType("text")
                        .HasColumnName("plandate");

                    b.Property<string>("Pm")
                        .HasColumnType("text")
                        .HasColumnName("pm");

                    b.Property<string>("PmName")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ProdDate")
                        .HasColumnType("text")
                        .HasColumnName("proddate");

                    b.Property<decimal?>("ProdQty")
                        .HasColumnType("numeric")
                        .HasColumnName("prodqty");

                    b.Property<string>("ProdTime")
                        .HasColumnType("text")
                        .HasColumnName("proddate_time");

                    b.Property<string>("Season")
                        .HasColumnType("text")
                        .HasColumnName("season");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StyleCd")
                        .HasColumnType("text")
                        .HasColumnName("stylecd");

                    b.Property<string>("WsNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wsno");

                    b.HasIndex(new[] { "Factory", "OpCd" }, "idx_smr_fac_op");

                    b.HasIndex(new[] { "OpCd" }, "idx_smr_op");

                    b.ToTable("worksheets_summary", "services");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.BomHeadEntity", b =>
                {
                    b.Property<string>("Category")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("category");

                    b.Property<string>("ColorVer")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("color_ver");

                    b.Property<string>("DevColorwayId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dev_colorway_id");

                    b.Property<string>("DevName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dev_name");

                    b.Property<string>("DevStyleNumber")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dev_style_number");

                    b.Property<string>("Dpa")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dpa");

                    b.Property<string>("Factory")
                        .IsRequired()
                        .HasColumnType("varhcar(5)")
                        .HasColumnName("factory");

                    b.Property<string>("Gender")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Id")
                        .HasColumnType("varchar(17)")
                        .HasColumnName("bom_id");

                    b.Property<string>("ModelId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("model_id");

                    b.Property<string>("NikeDev")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("nike_dev");

                    b.Property<decimal?>("NikeSendQty")
                        .HasColumnType("numeric)")
                        .HasColumnName("nike_send_qty");

                    b.Property<string>("PM")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pcc_pm");

                    b.Property<string>("PatternId")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("pattern_id");

                    b.Property<string>("PccOrg")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pcc_org");

                    b.Property<string>("ProdFactory")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("prod_factory");

                    b.Property<string>("Rev")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("bom_rev");

                    b.Property<string>("ReworkYN")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("rework_yn");

                    b.Property<string>("SampleEts")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("sample_ets");

                    b.Property<decimal?>("SampleQty")
                        .HasColumnType("numeric")
                        .HasColumnName("sample_qty");

                    b.Property<string>("SampleSize")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sample_size");

                    b.Property<string>("Season")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("season_cd");

                    b.Property<string>("StCd")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("st_cd");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("status");

                    b.Property<string>("StyleCd")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("style_cd");

                    b.Property<string>("SubStCd")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("sub_st_cd");

                    b.Property<string>("TD")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("td");

                    b.Property<string>("WsNo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ws_no");

                    b.Property<decimal?>("WsQty")
                        .HasColumnType("numeric")
                        .HasColumnName("ws_qty");

                    b.Property<string>("WsStatus")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ws_status");

                    b.HasIndex(new[] { "Factory", "WsNo" }, "bom_idx");

                    b.ToTable("pcc_plan_bom_head", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.IssueHeadEntity", b =>
                {
                    b.Property<DateTime>("CompleteDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("complete_date");

                    b.Property<DateTime>("CompleteDueDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("complete_due_date");

                    b.Property<string>("Factory")
                        .HasColumnType("varhcar(5)")
                        .HasColumnName("factory");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("issue_date");

                    b.Property<string>("Level1")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("issue_lv1");

                    b.Property<string>("Level2")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("issue_lv2");

                    b.Property<string>("Level3")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("issue_lv3");

                    b.Property<string>("OpCd")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("op_cd");

                    b.Property<decimal>("Seq")
                        .HasColumnType("numeric")
                        .HasColumnName("seq");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("status");

                    b.Property<string>("WsNo")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ws_no");

                    b.ToTable("pcc_plan_issue_head", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.IssueTailEntity", b =>
                {
                    b.Property<DateTime>("CompleteDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("complete_date");

                    b.Property<DateTime>("CompleteDueDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("complete_due_date");

                    b.Property<string>("Factory")
                        .HasColumnType("varhcar(5)")
                        .HasColumnName("factory");

                    b.Property<decimal>("LamSeq")
                        .HasColumnType("numeric")
                        .HasColumnName("lam_seq");

                    b.Property<string>("Level1")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("issue_lv1");

                    b.Property<string>("Level2")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("issue_lv2");

                    b.Property<string>("Level3")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("issue_lv3");

                    b.Property<string>("OpCd")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("op_cd");

                    b.Property<decimal>("PartSeq")
                        .HasColumnType("numeric")
                        .HasColumnName("part_seq");

                    b.Property<decimal>("Seq")
                        .HasColumnType("numeric")
                        .HasColumnName("seq");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("status");

                    b.Property<string>("WsNo")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ws_no");

                    b.ToTable("pcc_plan_issue_tail", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.MstMachineEntity", b =>
                {
                    b.Property<string>("AssetNo")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("asset_no");

                    b.Property<string>("Capacitance")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("capacitance");

                    b.Property<string>("Dept")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dept");

                    b.Property<string>("Dimension")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dimension");

                    b.Property<string>("DiscardDate")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("discard_date");

                    b.Property<string>("Division")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("op_div");

                    b.Property<string>("Grade")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("grade");

                    b.Property<string>("InDate")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("in_date");

                    b.Property<string>("MachineNo")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("machine_no");

                    b.Property<string>("Main")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("op_main");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("machine_name");

                    b.Property<string>("NameEng")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("machine_e_name");

                    b.Property<string>("Place")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("machine_place");

                    b.Property<string>("Power")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("power");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("machine_price");

                    b.Property<string>("PurDate")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("pur_date");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("numeric")
                        .HasColumnName("machine_qty");

                    b.Property<string>("Remarks")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remarks");

                    b.Property<string>("ReplaceDate")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("replace_date");

                    b.Property<decimal>("Seq")
                        .HasColumnType("numeric")
                        .HasColumnName("seq");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("status");

                    b.Property<string>("Sub")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("op_sub");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.Property<string>("UseYN")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("use_yn");

                    b.Property<string>("Vendor")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("vendor");

                    b.Property<string>("Weight")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("weight");

                    b.ToTable("pcc_machine_head", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.MstOpcdEntity", b =>
                {
                    b.Property<string>("Factory")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("factory");

                    b.Property<string>("OpCd")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("op_cd");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("numeric")
                        .HasColumnName("op_capacity");

                    b.Property<decimal>("LeadTime")
                        .HasColumnType("numeric")
                        .HasColumnName("op_leadtime");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("op_local_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("op_name");

                    b.Property<decimal>("SortNo")
                        .HasColumnType("numeric")
                        .HasColumnName("sort_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("status");

                    b.HasKey("Factory", "OpCd")
                        .HasName("pcc_mst_opcd_pkey");

                    b.HasIndex(new[] { "Factory", "OpCd" }, "pcc_mst_opcd_idx");

                    b.ToTable("pcc_mst_opcd", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.MstPlanIssuecdEntity", b =>
                {
                    b.Property<string>("Factory")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("factory");

                    b.Property<string>("IssueCd")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("issue_cd");

                    b.Property<decimal>("IssueLevel")
                        .HasColumnType("numeric")
                        .HasColumnName("issue_level");

                    b.Property<string>("IssueName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("issue_name");

                    b.Property<string>("ParentIssueCd")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("parent_issue_cd");

                    b.Property<string>("UseYN")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("use_yn");

                    b.HasKey("Factory", "IssueCd")
                        .HasName("pcc_mst_plan_issue_pkey");

                    b.ToTable("pcc_mst_plan_issue_cd", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.MstUserEntity", b =>
                {
                    b.Property<string>("Factory")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("factory");

                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Factory", "Id")
                        .HasName("pcc_user_info_pk");

                    b.ToTable("pcc_mst_user", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.PlanOpcdEntity", b =>
                {
                    b.Property<string>("Factory")
                        .HasColumnType("varhcar(5)")
                        .HasColumnName("factory");

                    b.Property<string>("WsNo")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ws_no");

                    b.Property<string>("OpCd")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("op_cd");

                    b.Property<string>("Chk")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("op_chk");

                    b.Property<string>("Date")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("op_ymd");

                    b.Property<string>("Passcard")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("passcard");

                    b.Property<decimal>("Qty")
                        .HasColumnType("numeric")
                        .HasColumnName("op_qty");

                    b.Property<string>("ReworkStat")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("rework_status");

                    b.Property<decimal>("Seq")
                        .HasColumnType("numeric")
                        .HasColumnName("seq");

                    b.HasKey("Factory", "WsNo", "OpCd")
                        .HasName("pcc_plan_opcd_pk");

                    b.ToTable("pcc_plan_opcd", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.PlanStatusEntity", b =>
                {
                    b.Property<string>("Factory")
                        .HasColumnType("varhcar(5)")
                        .HasColumnName("factory");

                    b.Property<string>("WsNo")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ws_no");

                    b.Property<string>("EmerYN")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("emer_yn");

                    b.Property<DateTime>("PlnaDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("plan_ymd");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remarks");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("request_ymd");

                    b.Property<decimal>("Seq")
                        .HasColumnType("numeric")
                        .HasColumnName("seq");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("plan_status");

                    b.Property<string>("WsStatus")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ws_status");

                    b.HasKey("Factory", "WsNo")
                        .HasName("pcc_plan_status_pkey");

                    b.ToTable("pcc_plan_status", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.ProdMaterialEntity", b =>
                {
                    b.Property<string>("Factory")
                        .HasColumnType("varhcar(5)")
                        .HasColumnName("factory");

                    b.Property<string>("InStatus")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("in_status");

                    b.Property<string>("LamDate")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("lam_date");

                    b.Property<string>("LamStatus")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("lam_status");

                    b.Property<string>("MatEnd")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("mat_date");

                    b.Property<string>("MatStart")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("mat_start");

                    b.Property<string>("MatStatus")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("mat_status");

                    b.Property<string>("SwatchDate")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("swatch_date");

                    b.Property<string>("SwatchStatus")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("swatch_status");

                    b.Property<string>("TracingPapper")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("tracing_paper");

                    b.Property<string>("WsCancel")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ws_cancel");

                    b.Property<string>("WsError")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ws_error");

                    b.Property<string>("WsNo")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ws_no");

                    b.ToTable("pcc_prod_material", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.ProdScanEntity", b =>
                {
                    b.Property<string>("Factory")
                        .HasColumnType("varhcar(5)")
                        .HasColumnName("factory");

                    b.Property<string>("WsNo")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ws_no");

                    b.Property<string>("OpCd")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("op_cd");

                    b.Property<decimal?>("ProdSeq")
                        .HasColumnType("numeric")
                        .HasColumnName("prod_seq");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("numeric")
                        .HasColumnName("prod_qty");

                    b.Property<string>("ReworkStatus")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("rework_status");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("prod_status");

                    b.Property<string>("Time")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("prod_time");

                    b.Property<string>("Ymd")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("prod_ymd");

                    b.HasKey("Factory", "WsNo", "OpCd", "ProdSeq")
                        .HasName("pcc_prod_scan_pk");

                    b.HasIndex(new[] { "Factory", "WsNo" }, "pcc_prod_group_idx");

                    b.HasIndex(new[] { "Factory", "WsNo", "OpCd", "ProdSeq", "Status" }, "pcc_prod_scan_idx");

                    b.ToTable("pcc_prod_scan", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.ReworkDetailEntity", b =>
                {
                    b.Property<string>("Factory")
                        .HasColumnType("varhcar(5)")
                        .HasColumnName("factory");

                    b.Property<decimal>("LamSeq")
                        .HasColumnType("numeric")
                        .HasColumnName("lam_seq");

                    b.Property<decimal>("PartSeq")
                        .HasColumnType("numeric")
                        .HasColumnName("part_seq");

                    b.Property<string>("Remark")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("rework_remarks");

                    b.Property<decimal>("Seq")
                        .HasColumnType("numeric")
                        .HasColumnName("seq");

                    b.Property<string>("WsNo")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ws_no");

                    b.ToTable("pcc_plan_rework_detail", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.ReworkHeadEntity", b =>
                {
                    b.Property<string>("CompleteDate")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("complete_date");

                    b.Property<string>("Factory")
                        .HasColumnType("varhcar(5)")
                        .HasColumnName("factory");

                    b.Property<string>("OccurDate")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("occur_date");

                    b.Property<string>("OpCd")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("op_cd");

                    b.Property<string>("Remark")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("rework_head_remarks");

                    b.Property<decimal>("Seq")
                        .HasColumnType("numeric")
                        .HasColumnName("seq");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("status");

                    b.Property<string>("WsNo")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ws_no");

                    b.ToTable("pcc_plan_rework_head", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.PCC.ReworkOpcdEntity", b =>
                {
                    b.Property<string>("CompleteDate")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("complete_date");

                    b.Property<string>("Factory")
                        .HasColumnType("varhcar(5)")
                        .HasColumnName("factory");

                    b.Property<string>("OpCd")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("rework_op_cd");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("numeric")
                        .HasColumnName("rework_qty");

                    b.Property<decimal>("Seq")
                        .HasColumnType("numeric")
                        .HasColumnName("seq");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(2)")
                        .HasColumnName("status");

                    b.Property<string>("WsNo")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ws_no");

                    b.ToTable("pcc_plan_rework_opcd", "pcc");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.RTLS.TbErpPlanDataEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("int64")
                        .HasColumnName("id");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("sys_update_dt");

                    b.Property<string>("BeaconTagId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("beacon_tag_id");

                    b.Property<string>("BoxNo")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("box_no");

                    b.Property<string>("Category")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("category");

                    b.Property<string>("Ce")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pcc_ce");

                    b.Property<string>("ColorwayId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("colorway_id");

                    b.Property<string>("Factory")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("factory");

                    b.Property<string>("Gender")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("gender");

                    b.Property<string>("Modelname")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("PassType")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("pass_type");

                    b.Property<decimal>("PcardQty")
                        .HasColumnType("numeric")
                        .HasColumnName("pcard_qty");

                    b.Property<string>("Pe")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pcc_pe");

                    b.Property<string>("PlanDate")
                        .HasColumnType("varchar(8)")
                        .HasColumnName("plan_date");

                    b.Property<string>("Pm")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pcc_pm");

                    b.Property<string>("ProdFactory")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("prod_factory");

                    b.Property<string>("SampleEts")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasColumnName("sample_ets");

                    b.Property<string>("Season")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("season");

                    b.Property<decimal>("Seq")
                        .HasColumnType("numeric")
                        .HasColumnName("seq");

                    b.Property<string>("SizeCd")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("size_cd");

                    b.Property<string>("Stcd")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("st_cd");

                    b.Property<string>("SubRemark")
                        .HasColumnType("varchar(400)")
                        .HasColumnName("sub_remark");

                    b.Property<string>("Substcd")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sub_st_cd");

                    b.Property<string>("Te")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pcc_te");

                    b.Property<string>("Wsno")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ws_no");

                    b.HasKey("Id", "UpdateDate")
                        .HasName("tb_erp_plan_data_pkey");

                    b.HasIndex(new[] { "UpdateDate" }, "date_idx");

                    b.HasIndex(new[] { "Modelname" }, "model_idx");

                    b.HasIndex(new[] { "PassType" }, "passtype_idx");

                    b.HasIndex(new[] { "Pm" }, "pm_idx");

                    b.HasIndex(new[] { "Pm", "Modelname" }, "pm_model_idx");

                    b.HasIndex(new[] { "Season" }, "season_idx");

                    b.HasIndex(new[] { "BeaconTagId" }, "tagid_idx");

                    b.HasIndex(new[] { "Wsno" }, "wsno_idx");

                    b.ToTable("tb_erp_plan_data", "rtls");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.RTLS.TbEslLocationEntity", b =>
                {
                    b.Property<string>("BeaconTagId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("beacon_tag_id");

                    b.Property<string>("ProcessLoc")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("process_loc");

                    b.Property<DateTime>("UpdateDt")
                        .HasColumnType("timestamp")
                        .HasColumnName("sys_update_dt");

                    b.ToTable("tb_esl_location", "rtls");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Production.RTLS.TbProcessLocEntity", b =>
                {
                    b.Property<string>("Level1")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("level1");

                    b.Property<string>("Level2")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("level2");

                    b.Property<string>("LocName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("loc_name");

                    b.Property<string>("ProcessLoc")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("process_loc");

                    b.Property<string>("ProcessLocName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("process_loc_name");

                    b.Property<string>("StepCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("step_code");

                    b.ToTable("tb_process_loc", "rtls");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Department.DeptRnREntity", b =>
                {
                    b.HasOne("CSG.MI.FDW.EF.Entities.Department.DeptEntity", "DeptNavigation")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("dept_rnr_fkey");

                    b.Navigation("DeptNavigation");
                });

            modelBuilder.Entity("CSG.MI.FDW.EF.Entities.Feedback.FeedbackEntity", b =>
                {
                    b.HasOne("CSG.MI.FDW.EF.Entities.Feedback.CategoryEntity", "CategoryNavigation")
                        .WithMany()
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_feedback_category");

                    b.HasOne("CSG.MI.FDW.EF.Entities.Feedback.SystemEntity", "SystemNavigation")
                        .WithMany()
                        .HasForeignKey("System")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_feedback_system");

                    b.Navigation("CategoryNavigation");

                    b.Navigation("SystemNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
